name: Adorable CI/CD
on:
  pull_request:
    branches:
      - master
    paths:
      - boys/**
jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: |
          echo PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }') >> $GITHUB_ENV
          echo PR_TITLE=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH") >> $GITHUB_ENV
          echo PR_URL=$(jq --raw-output .pull_request.html_url "$GITHUB_EVENT_PATH") >> $GITHUB_ENV
          echo PR_USER=$(jq --raw-output .pull_request.user.login "$GITHUB_EVENT_PATH") >> $GITHUB_ENV
      - run: printenv
      - name: Send email when pull request
        if: ${{ success() }}
        uses: dawidd6/action-send-mail@v3.5.0
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 又有小可爱发女装啦~
          to: 1598651543@qq.com
          from: Adorable
          body: |
            好耶，又有小可爱发女装啦~
            小可爱：${{ env.PR_USER }}
            标题：${{ env.PR_TITLE }}
            链接：${{ env.PR_URL }}
